version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: blade-knowledge-demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: blade_knowledge_demo
      MYSQL_USER: blade
      MYSQL_PASSWORD: blade123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - blade-network

  # Redis 缓存
  redis:
    image: redis:6.2-alpine
    container_name: blade-knowledge-demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blade-network

  # 知识管理演示服务
  knowledge-demo:
    build: .
    container_name: blade-knowledge-demo
    ports:
      - "8100:8100"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/blade_knowledge_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: blade
      SPRING_DATASOURCE_PASSWORD: blade123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - blade-network

volumes:
  mysql_data:
  redis_data:

networks:
  blade-network:
    driver: bridge
