spring:
  # 开发环境数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/blade_knowledge_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  
  # 开发环境 Redis 配置
  redis:
    host: localhost
    port: 6379

# 开发环境日志配置
logging:
  level:
    org.springblade.knowledge.demo: debug
    com.baomidou.mybatisplus: debug
