#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

  autoconfigure:
    exclude:
      # 数据库相关
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceAutoConfigure

      # Redis相关
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
      - org.springblade.core.redis.config.BladeRedisCacheAutoConfiguration
      - org.springblade.core.redis.config.RedisPubSubConfiguration
      - org.springblade.core.redis.config.RedisTemplateConfiguration
      - org.springblade.core.tool.config.RedisConfiguration
      - qknow.common.core.redis.RedisCache

      # 安全相关（LLM模块不需要数据库权限控制）
      - org.springblade.core.secure.config.SecureConfiguration
      - org.springblade.core.secure.config.SecureProperties
      - org.springblade.core.datascope.config.DataScopeConfiguration
      - org.springblade.core.tenant.config.TenantConfiguration
      - org.springblade.core.mp.config.MybatisPlusConfiguration

      # MyBatis相关
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration

      # 事务相关
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration

      # Actuator相关（可选，如果不需要监控端点）
      - org.springframework.boot.actuate.autoconfigure.cache.CachesEndpointAutoConfiguration

# SpringBlade框架功能开关配置
# 通过条件化配置控制各模块功能启用/禁用
blade:
  database:
    enabled: false    # 禁用数据库功能
  redis:
    enabled: false    # 禁用Redis功能
  security:
    enabled: false    # 禁用安全功能
  tenant:
    enabled: false    # 禁用租户功能
  datascope:
    enabled: false    # 禁用数据范围功能
  mybatis:
    enabled: false    # 禁用MyBatis功能
  transaction:
    enabled: false    # 禁用事务功能

# Neo4j配置（通过Nacos加载）
# neo4j:
#   uri: ${neo4j.uri:bolt://127.0.0.1:7687}
#   user: ${neo4j.user:neo4j}
#   password: ${neo4j.password:12345678}

# 日志配置
logging:
  level:
    org:
      neo4j:
        driver: INFO
      springframework:
        data:
          neo4j: INFO
    tech.qiantong: debug
