# 项目相关配置
qknow:
  # 名称
  name: qKnow
  # 版本
  version: 3.8.8
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/qknow/uploadPath，Linux配置 /home/qknow/uploadPath） -- 需要和 file 模块保持一致
  profile: ${user.dir}/upload/
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8090
  port: 8090
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    tech.qiantong: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
    #万能密码 配置为空则不生效
    universalPassword:

# Spring配置
spring:
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
  thymeleaf:
    prefix: classpath:/dist/
    mode: HTML
    encoding: utf-8
    cache: false
    # 添加以下配置
#    enabled: false  # 禁用Thymeleaf，因为这是前后端分离项目
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev  # 默认激活的环境，可以在启动时覆盖
  config:
    import:
      # 基础配置文件
      - "application-${spring.profiles.active}.yml"
      
      # 配置管理说明：
      # 1. 项目使用Nacos配置中心，建议将Neo4j等配置放在Nacos中统一管理
      # 2. 避免跨模块直接引用配置文件，因为classpath可能无法访问
      # 3. 通过bootstrap.yml中的Nacos配置自动加载共享配置
      
      # 当前模块已通过bootstrap.yml配置了Nacos，会自动加载：
      # - blade.yaml (共享配置)
      # - blade-${spring.profiles.active}.yaml (环境特定配置)
      # - ${spring.application.name}-${spring.profiles.active}.yaml (应用特定配置)
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 3000MB
      # 设置总上传的文件大小
      max-request-size: 3000MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 600

# MyBatis配置
# mybatis:
  # 搜索指定包别名
  # typeAliasesPackage: tech.qiantong.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  # mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mybatis/mybatis-config.xml

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: tech.qiantong.**.dataobject, tech.qiantong.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    # 关闭 MyBatis-Plus 的 Banner
    banner: false
    db-config:
      # 主键类型 AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      idType: AUTO
      # 全局逻辑删除字段名
      logic-delete-field: delFlag
      # 逻辑已删除值（默认为1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为0）
      logic-not-delete-value: 0
      # 字段验证策略之 insert,在 insert 的时候的字段验证策略 IGNORED 忽略 NOT_NULL 非NULL NOT_EMPTY 非空 DEFAULT 默认 NEVER 不加入 SQL
      insertStrategy: NOT_NULL
      # 字段验证策略之 update,在 update 的时候的字段验证策略
      updateStrategy: NOT_NULL
      # 字段验证策略之 select,在 select 的时候的字段验证策略既 wrapper 根据内部 entity 生成的 where 条件
      where-strategy: NOT_NULL

mybatis-plus-join:
  # 是否打印 mybatis plus join banner，默认true
  banner: false
  # 全局启用副表逻辑删除，默认true。关闭后关联查询不会加副表逻辑删除
  sub-table-logic: true
  # 拦截器MappedStatement缓存，默认 true
  ms-cache: true
  # 表别名(默认 t)
  table-alias: t
  # 副表逻辑删除条件的位置，支持 WHERE、ON，默认 ON
  logic-del-type: on

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger 分组配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'system'
      paths-to-match: '/**'
      packages-to-scan: tech.qiantong.qknow.module.system.controller
    - group: 'app'
      paths-to-match: '/**'
      packages-to-scan: tech.qiantong.qknow.module.app.controller
    - group: 'dm'
      paths-to-match: '/**'
      packages-to-scan: tech.qiantong.qknow.module.dm.controller
    - group: 'ext'
      paths-to-match: '/**'
      packages-to-scan: tech.qiantong.qknow.module.ext.controller
    - group: 'kmc'
      paths-to-match: '/**'
      packages-to-scan: org.springblade.knowledge.kmc.controller
# Swagger 增强配置
knife4j:
  enable: true
  documents:
    -
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/*
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: 127.0.0.1:8080
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md
    enable-search: false
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: MIT | Copyright  2025-[江苏千桐科技有限公司])
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: true
    enable-group: true
  cors: false
  production: false
  basic:
    enable: true
    username: qknow
    password: qknow12313

# Text2Cypher API 配置
text2cypher:
  api:
    base-url: http://localhost:8003/api/v1
    timeout: 60000
    retry:
      max-attempts: 3
      backoff-delay: 1000
  llm:
    default-model: ark-model
    default-database: neo4j
    default-workflow: text2cypher_with_1_retry_and_output_check
