#服务器端口
server:
  port: 8108

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

# MyBatis配置
mybatis-plus:
  type-aliases-package: org.springblade.knowledge.kmc.dal.dataobject
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
